In [ ]:
# 1) 
import numpy as np


num_list = [12.23, 13.32, 100, 36.32]
print("Original List:", num_list)


num_array = np.array(num_list)
print("One Dimensional Array:", num_array)



Original List: [12.23, 13.32, 100, 36.32]
One Dimensional Array: [ 12.23  13.32 100.    36.32]


In [2]:
#2
import numpy as np

arr = np.array([[2,5,8], [3,6,9], [4,7,10]])
print(arr.T)



[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
#3
import numpy as np

arr = np.zeros(10)
print(arr)
arr[6] = 11
print("Updated sixth value to 11:", arr)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated sixth value to 11: [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [5]:
#4
import numpy as np

arr = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])
print("Original Array: ", arr)
reversed_arr = arr[::-1]
print("Reverse array: ", reversed_arr)



Original Array:  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:  [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [14]:
#5
import numpy as np

arr = np.ones((5, 5))
print("Original array: \n", arr)
arr[1:-1, 1:-1] = 0
print("1 on the border and 0 inside in the array \n",arr)



Original array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
#6
import numpy as np
arr = np.zeros((5, 5))
print("Original array: \n", arr)
arr[1:-1, 1:-1] = 1
print("1 on the border and 0 inside in the array \n", arr)


Original array: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
1 on the border and 0 inside in the array 
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
#7
import numpy as np

checkerboard = np.zeros((8, 8))
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
print("Checkerboard pattern: \n", checkerboard)



Checkerboard pattern: 
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [21]:
#8
import numpy as np

my_list = [1, 2, 3, 4, 5, 6, 7, 8]
list_array = np.array(my_list)
print("List to array:\n",list_array)

my_tuple = ((8, 4, 6), (1, 2, 3))
tuple_array = np.array(my_tuple)
print("Tuple to array:\n",tuple_array)





List to array:
 [1 2 3 4 5 6 7 8]
Tuple to array:
 [[8 4 6]
 [1 2 3]]


In [24]:
#9
import numpy as np

arr = np.array([10, 20, 30])
print("Original array: \n", arr)
new_arr = np.append(arr, [40, 50, 60, 70, 80, 90])
print("After append values to the end of the array:\n", new_arr)



Original array: 
 [10 20 30]
After append values to the end of the array:
 [10 20 30 40 50 60 70 80 90]


In [2]:
#10
import numpy as np

complex_arr = np.array([1.00000000+0j, 0.70710678 + 0.70710678j])

real_part = np.real(complex_arr)
imag_part = np.imag(complex_arr)

print("Original array \n", complex_arr)
print("Real part of the array: \n", real_part)
print("Imaginary part of the array: \n", imag_part)




Original array 
 [1.        +0.j         0.70710678+0.70710678j]
Real part of the array: 
 [1.         0.70710678]
Imaginary part of the array: 
 [0.         0.70710678]


In [4]:
#11
import numpy as np

arr = np.array([10, 20, 30], dtype=np.int64)

size = arr.size

element_size = arr.itemsize

total_size = size*element_size

print("Size of the array:", size)
print("Lenght of one array element in bytes:", element_size)
print("Total bytes consumed by the elements of the array:", total_size)


Size of the array: 3
Lenght of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


In [5]:
#12
import numpy as np

array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])

common_values = np.intersect1d(array1, array2)

print("Array1:", array1)
print("Array2:", array2)
print("Common values between two arrays:")
print(common_values)


Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values between two arrays:
[10 40]


In [7]:
#13
import numpy as np

array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])

set_difference = np.setdiff1d(array1, array2)

print("Array1:", array1)
print("Array2:", array2)
print("Set difference between two arrays:", set_difference)



Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70 90]
Set difference between two arrays: [ 0 20 60 80]


In [10]:
#14
import numpy as np

array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])

xor_values = np.setxor1d(array1, array2)

print("Array1:", array1)
print("Array2:", array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(xor_values)


Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


In [11]:
#15
import numpy as np

a = np.array([1, 2])
b = np.array([4, 5])

print("Array a:", a)
print("Array b:", b)
print("a > b")
print(a > b)
print("a >= b")
print(a >= b)
print("a < b")
print(a < b)
print("a <= b")
print(a <= b)

Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


In [ ]:
#15
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

np.savetxt("array.txt", arr, fmt="%d")
print("Array saved to 'array.txt'")


Array saved to 'array.txt'


In [ ]:
#16
import numpy as np

original_array = np.array([[10, 20, 30], [20, 40, 50]])

flattened_array = original_array.ravel()

print("Orginal array:")
print(original_array)
print("New flattened array:")
print(flattened_array)


Orginal array:
[[10 20 30]
 [20 40 50]]
New flattened array:
[10 20 30 20 40 50]


In [ ]:
#17
import numpy as np

x = np.array([[2, 4, 6], [6, 8, 10]])

print(x)
print("Data type of the array x is:", x.dtype)
x_float = x.astype(np.float64)

print("New Type:", x_float.dtype)
print(x_float)


[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int64
New Type: float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


In [23]:
#18
import numpy as np

arr = np.zeros((3, 3, 3), dtype=float)

arr = np.diag([1, 1, 1])

print(arr)



[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#19
import numpy as np

arr = np.array([
    [0., 0., 0.],
    [1., 0., 0.],
    [1., 1., 0.],
    [1., 1., 1.]
])
print(arr)


[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [1]:
#20
import numpy as np

arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2 = np.array([[0, 2, 4], [6, 8, 10]])

result = np.concatenate((arr1, arr2), axis=1)

print("Concatenate Array:")
print(result)



Concatenate Array:
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [7]:
#21
import numpy as np

arr = np.array([10, 20, 30])

print("Is the array writeable?", arr.flags.writeable)

arr.flags.writeable = False
print("Array is now read-only!")

try:
    arr[0] = 100
except ValueError as e:
    print("Error:", e)





Is the array writeable? True
Array is now read-only!
Error: assignment destination is read-only


In [9]:
#22
import numpy as np

arr = np.arange(12).reshape(3, 4)

new_arr = arr * 3

print("Original array elements:")
print(arr)

print("\n New array elements:")
print(new_arr)



Original array elements:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 New array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [10]:
#23
import numpy as np

arr = np.array([[0, 1], [2, 3], [4, 5]])

arr_list = arr.tolist()

print("Original array elements:")
print(arr)

print("\nArray to list:")
print(arr_list)



Original array elements:
[[0 1]
 [2 3]
 [4 5]]

Array to list:
[[0, 1], [2, 3], [4, 5]]


In [12]:
#24
import numpy as np

arr = np.random.rand(10)

print("Original array elements:")
print(arr)

arr_list = arr.tolist()
print("\nConverted to Python list:")
print(arr_list)

np.set_printoptions(precision=3, suppress=True)
print("\nPrint array values with precision 3:")
print(arr)


Original array elements:
[0.477 0.267 0.901 0.941 0.692 0.31  0.467 0.092 0.964 0.764]

Converted to Python list:
[0.4768384322375724, 0.26664487258468417, 0.9014691095685714, 0.941445483981228, 0.6919108904879393, 0.3096836192061747, 0.4671026612442092, 0.09207798261125177, 0.9641763674177615, 0.7641119200884059]

Print array values with precision 3:
[0.477 0.267 0.901 0.941 0.692 0.31  0.467 0.092 0.964 0.764]


In [13]:
#25
import numpy as np

arr = np.array([0.00000000016, 1.6, 1200, 0.235])

print("Original array:")
print(arr)

np.set_printoptions(suppress=True, precision=3)

print("\nArray without scientific notation:")
print(arr)




Original array:
[   0.       1.6   1200.       0.235]

Array without scientific notation:
[   0.       1.6   1200.       0.235]


In [14]:
#26
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

new_column = np.array([
    [100], 
    [200]
])

result = np.concatenate((arr, new_column), axis=1)

print("Array after adding extra column:")
print(result)


Array after adding extra column:
[[ 10  20  30 100]
 [ 40  50  60 200]]


In [16]:
#27
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Original array:")
print(arr)

indexes_to_remove = [0, 3, 4]

new_arr = np.delete(arr, indexes_to_remove)

print("\nArray after removing selected elements:")
print(new_arr)


Original array:
[ 10  20  30  40  50  60  70  80  90 100]

Array after removing selected elements:
[ 20  30  60  70  80  90 100]
